version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.11.4
        environment:
          SURREAL_URL: ws://localhost:8000/rpc
          SURREAL_USER: root
          SURREAL_PASSWORD: root
          SURREAL_NAMESPACE: myns
          SURREAL_DATABASE: mydb
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: mysecretpassword
          POSTGRES_DATABASE: dvdrental          
      - image: floodplain/dvdrental:latest
        name: postgres
        environment:
          POSTGRES_PASSWORD: mysecretpassword
      - image: surrealdb/surrealdb:latest
        name: surreal
        command: start --log trace --user root --pass root --pass root file://database.db
    steps:
      - setup_remote_docker:
          version: 20.10.14
      - checkout
      - run: python --version
      - run: pip install -r requirements.txt
      - run: pip install pylint
      - run: pylint --fail-under=8 migrate.py
      - run: docker ps -a
      - run: docker ps -q
      - run: python migrate.py
      - run: export SURREAL_CONTAINER=$(docker ps | grep surrealdb:latest |  awk '{ print $1 }')
      - run: docker stop $SURREAL_CONTAINER
      - run: docker commit $SURREAL_CONTAINER flyaruu/surrealdb-dvdrental:${CIRCLE_SHA1}
      - run: docker exec surreal du -hs *
      - run: echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run: docker push flyaruu/surrealdb-dvdrental:${CIRCLE_SHA1}
      - run: docker tag flyaruu/surrealdb-dvdrental:${CIRCLE_SHA1} flyaruu/surrealdb-dvdrental:latest
      - run: docker push flyaruu/surrealdb-dvdrental:latest
